name: Java Build Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build API Gateway
      run: mvn -f services/api-gateway/pom.xml clean install

    - name: Build User Service
      run: mvn -f services/user-service/pom.xml clean install

    - name: Build Product Service
      run: mvn -f services/product-service/pom.xml clean install

    - name: Build Order Service
      run: mvn -f services/order-service/pom.xml clean install
